apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: profile-service
build:
  artifacts:
    - image: hireverse/profile-server
      docker:
        dockerfile: Dockerfile
        target: production
manifests:
  rawYaml:
    - k8s/*
